In [ ]:
# logic here - 
# read the data and then viz it for the first 100 samples
# do not apply anything from bag of tricks first, just see if it works
# plot the results accordingly
# revisit after first 100 samples train for the 3 epochs

In [3]:
import pandas as pd
from sklearn.ensemble import StackingRegressor
from xgboost import XGBRegressor

In [8]:
# Read the predictions and ground truth from the CSV file
data = pd.read_csv('/home/ssj/CS640-Originality-Score-Project/data/models-output.csv')
print(data.head(10))
data.dropna(inplace=True)
# y_pred = data.iloc[:, :3].values

# print(y_pred)
y_true = data.iloc[:, 3].values
print(y_true)

   Open AI Classfier  Zero GPT  GPT Zero  Label          ID
0                0.0       1.0       1.0    0.0  63,064,638
1                0.0       1.0       1.0    0.0     279,621
2                0.0       0.0       1.0    0.0     287,229
3                0.0       0.0       0.0    0.0    26712375
4                0.0       0.0       0.0    0.0    38894426
5                0.0       0.0       1.0    0.0    26709147
6                0.0       0.0       1.0    0.0    15169469
7                0.0       0.0       0.0    0.0     5723289
8                0.0       0.0       0.0    0.0    62862417
9                0.0       0.0       1.0    0.0    62166018
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]


In [55]:
# Read the predictions and ground truth from the CSV file
data = pd.read_csv('/home/ssj/CS640-Originality-Score-Project/data/AI_data.csv')

# drop columns
data = data.drop(['Unnamed: 8', 'DetectGPT', 'GPT Zero '], axis=1)
data.dropna(inplace=True)

# 1 is AI / 0 is Human
data['Label'] = 1 # 1 is the highest probability, which means def AI 

# viz the data
data.head(10)

In [ ]:
# col = data.columns
# print(col)

# create predictions to train the meta regressor
y_pred = data.iloc[:, 2:6].values

# create ground truth labels
y_true = data['Label'].values

In [56]:
print(y_pred)

[[4.000000e+00 2.618200e+01 1.461400e+01 7.820000e-01]
 [4.000000e+00 4.580000e+01 4.440900e+01 1.378000e+00]
 [4.000000e+00 6.953800e+01 9.929000e+01 1.533000e+00]
 [4.000000e+00 2.633300e+01 1.742700e+01 1.396000e+00]
 [4.000000e+00 2.810830e+02 8.526870e+02 1.506000e+00]
 [4.000000e+00 1.399091e+03 4.572934e+03 1.171000e+00]
 [4.000000e+00 4.415400e+01 3.923200e+01 1.510000e+00]
 [4.000000e+00 5.578600e+01 6.496100e+01 1.091000e+00]
 [4.000000e+00 6.546200e+01 1.378700e+02 1.365000e+00]
 [4.000000e+00 4.683300e+01 5.467600e+01 1.094000e+00]
 [4.000000e+00 3.521400e+01 7.677500e+01 1.196000e+00]
 [4.000000e+00 3.290900e+01 2.503800e+01 2.107000e+00]
 [4.000000e+00 6.541700e+01 5.325500e+01 1.580000e-01]
 [4.000000e+00 5.670000e+01 1.015740e+02 1.207000e+00]
 [4.000000e+00 1.462310e+02 3.848950e+02 8.970000e-01]
 [4.000000e+00 6.629400e+01 8.812900e+01 1.286000e+00]
 [4.000000e+00 1.936400e+01 1.433400e+01 1.252000e+00]
 [4.000000e+00 2.570000e+01 1.972100e+01 1.079000e+00]
 [4.000000

In [57]:
print(y_true)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [1]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

# Read the predictions and ground truth from the CSV file
# data = pd.read_csv('../data/models-output.csv')
# data.dropna(inplace=True)
# y_pred = data.iloc[:, :3].values
# y_true = data.iloc[:, 3].values

# Standardize the input features
scaler = StandardScaler()
y_pred = scaler.fit_transform(y_pred)

# Define an MLPRegressor to learn the weights of the models
mlp = MLPRegressor(hidden_layer_sizes=(1,), activation='relu', solver='adam', max_iter=1000)

# Fit the MLPRegressor on the predictions and ground truth
mlp.fit(y_pred, y_true)

# Get the learned weights from the MLPRegressor
weights = mlp.coefs_[0]

# Normalize the weights to sum up to 1
weights /= np.sum(weights)

print("Weights obtained:\n")
print("Open AI Classifier:", weights[0][0])
print("Zero GPT:", weights[1][0])
print("GPT Zero:", weights[2][0])
print("\n")
y_combined = np.dot(y_pred, weights)
print("Predicted labels:\n", y_combined)


NameError: name 'y_pred' is not defined

In [58]:
# # load your original feature data into X and your target variable into y
# X = pd.read_csv('original_features.csv')
# y = pd.read_csv('target_variable.csv')

# # load the CSV file containing the outputs of your pretrained models
# pretrained_outputs = pd.read_csv('pretrained_outputs.csv')

# # concatenate the pretrained outputs with your original feature data
# X = pd.concat([X, pretrained_outputs], axis=1)

# create the stacked regressor with XGBoost as the final estimator
stacked_regressor = StackingRegressor(
    estimators=[],
    final_estimator=XGBRegressor()
)

# fit the stacked regressor on your data
stacked_regressor.fit(y_pred, y_true)

# make predictions with the stacked regressor
# y_pred = stacked_regressor.predict(X_test)

ValueError: Invalid 'estimators' attribute, 'estimators' should be a non-empty list of (string, estimator) tuples.

In [ ]:
#A Multilayer perceptron to compute weights of each of the AI detection models according to the outputs they predicted

import numpy as np
import pandas as pd
from sklearn.neural_network import MLPRegressor
frpm

# Read the predictions and ground truth from the CSV file
data = pd.read_csv('../data/models-output.csv')
data.dropna(inplace=True)
y_pred = data.iloc[:, :3].values

print(y_pred)
y_true = data.iloc[:, 3].values
print(y_true)

# Define an MLPRegressor to learn the weights of the models
mlp = MLPRegressor(hidden_layer_sizes=(1,), max_iter=1000)

# Fit the MLPRegressor on the predictions and ground truth
mlp.fit(y_pred, y_true)

# Get the learned weights from the MLPRegressor
weights = mlp.coefs_[0]

# Normalize the weights to sum up to 1
weights /= np.sum(weights)
print("Weights obtained:\n")
print("Open AI Classifier:", weights[0][0])
print("Zero GPT:", weights[1][0])
print("GPT Zero:", weights[2][0])
print("\n")
y_combined = np.dot(y_pred, weights)
print("Predicted labels:\n", y_combined)
# print(len(y_combined))


In [24]:
# new mlp with the final code
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler

# Read the predictions and ground truth from the CSV file
data = pd.read_csv('/home/ssj/CS640-Originality-Score-Project/data/AI_data.csv')

# drop columns
data = data.drop(['Unnamed: 8', 'DetectGPT', 'GPT Zero '], axis=1)
data.dropna(inplace=True)

# 1 is AI / 0 is Human
data['Label'] = 1 # 1 is the highest probability, which means def AI 

# viz the data
# data.head(10)

# col = data.columns
# print(col)

# create predictions to train the MLP regressor
y_pred = data.iloc[:, 2:6].values

# create ground truth labels
y_true = data['Label'].values

# Read the predictions and ground truth from the CSV file
# data = pd.read_csv('../data/models-output.csv')
# data.dropna(inplace=True)
# y_pred = data.iloc[:, :3].values
# y_true = data.iloc[:, 3].values

# Standardize the input features
scaler = StandardScaler()
y_pred = scaler.fit_transform(y_pred)

# Define an MLPRegressor to learn the weights of the models
mlp = MLPRegressor(hidden_layer_sizes=(10,7,3), activation='relu', solver='adam', max_iter=10000)

# Fit the MLPRegressor on the predictions and ground truth
mlp.fit(y_pred, y_true)

# Get the learned weights from the MLPRegressor
weights = mlp.coefs_[0]

# Calculate the sum of the absolute values of the weights
abs_weights_sum = np.sum(np.abs(weights))

# Normalize the weights to sum up to 1
normalized_weights = weights / abs_weights_sum

print("Weights obtained:\n")
print("Open AI Classifier:", normalized_weights[0][0])
print("Zero GPT:", normalized_weights[1][0])
print("GPT Zero:", normalized_weights[2][0])
print("\n")
y_combined = np.dot(y_pred, normalized_weights)
print("Predicted labels:\n", y_combined)
print("sum of weights:", np.abs(normalized_weights[0][0])+np.abs(normalized_weights[1][0])+np.abs(normalized_weights[2][0]))





# # Get the learned weights from the MLPRegressor
# weights = mlp.coefs_[0]

# # Calculate the sum of the absolute values of the weights along the rows
# abs_weights_sum = np.sum(np.abs(weights), axis=1)

# # Normalize the weights row-wise to sum up to 1
# normalized_weights = weights / abs_weights_sum[:, np.newaxis]

# print("Weights obtained:\n")
# print("Open AI Classifier:", normalized_weights[0][0])
# print("Zero GPT:", normalized_weights[1][0])
# print("GPT Zero:", normalized_weights[2][0])
# print("\n")
# y_combined = np.dot(y_pred, normalized_weights)
# print("Predicted labels:\n", y_combined)
# print("sum of weights:", np.sum(normalized_weights, axis=1))



# Get the learned weights from the MLPRegressor
weights = mlp.coefs_[0]

# Calculate the sum of the absolute values of the weights along the columns
abs_weights_sum = np.sum(np.abs(weights), axis=0)

# Normalize the weights column-wise to sum up to 1
normalized_weights = weights / abs_weights_sum

print("Weights obtained:\n")
print("Open AI Classifier:", normalized_weights[0][0])
print("Zero GPT:", normalized_weights[1][0])
print("GPT Zero:", normalized_weights[2][0])
print("\n")
y_combined = np.dot(y_pred, normalized_weights)
print("Predicted labels:\n", y_combined)
print("sum of weights:", np.sum(normalized_weights, axis=0))


Weights obtained:

Open AI Classifier: 0.2538721669893282
Zero GPT: -0.03303723171850475
GPT Zero: -0.336352819182487


Predicted labels:
 [[ 0.6753484   0.38014216  0.00606358 ...  0.04408033  0.44094343
   0.38341928]
 [ 0.14645544  0.20159932 -0.16764337 ...  0.30691699  0.18962176
   0.13023946]
 [-0.02453126  0.07005697 -0.2009443  ...  0.3443073   0.1057537
   0.03402207]
 ...
 [ 0.13832059  0.12282715 -0.14582533 ...  0.2626728   0.18190036
   0.1099813 ]
 [ 0.79049215  0.0394602   0.14136914 ... -0.27290917  0.50665476
   0.39774645]
 [ 0.4368316   0.04663906 -0.0215983  ... -0.02132938  0.35239732
   0.26566929]]
sum of weights: [-0.49225567 -0.878974   -0.42836428 -0.09255096  0.114144    0.07123152
 -0.34193488  0.32773551  0.13269562 -0.12160887]


In [25]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin

# Custom activation function to normalize the output
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

class SoftmaxTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return np.apply_along_axis(softmax, 1, X)

data = pd.read_csv('/home/ssj/CS640-Originality-Score-Project/data/AI_data.csv')
data = data.drop(['Unnamed: 8', 'DetectGPT', 'GPT Zero '], axis=1)
data.dropna(inplace=True)

data['Label'] = 1
y_pred = data.iloc[:, 2:6].values
y_true = data['Label'].values

scaler = StandardScaler()
y_pred = scaler.fit_transform(y_pred)

mlp = MLPRegressor(hidden_layer_sizes=(10,7,3,1), activation='relu', solver='adam', max_iter=10000)

# Create a pipeline to apply the custom activation function
mlp_pipeline = Pipeline([
    ('mlp', mlp),
    ('softmax', SoftmaxTransformer())
])

mlp_pipeline.fit(y_pred, y_true)

weights = mlp.coefs_[-1]  # Access the last layer weights

abs_weights_sum = np.sum(np.abs(weights))

normalized_weights = weights / abs_weights_sum

print("Weights obtained:\n")
print("Open AI Classifier:", normalized_weights[0][0])
print("Zero GPT:", normalized_weights[1][0])
print("GPT Zero:", normalized_weights[2][0])
print("\n")
y_combined = np.dot(y_pred, normalized_weights)
print("Predicted labels:\n", y_combined)
print("sum of weights:", np.abs(normalized_weights[0][0])+np.abs(normalized_weights[1][0])+np.abs(normalized_weights[2][0]))


TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' 'MLPRegressor(hidden_layer_sizes=(10, 7, 3, 1), max_iter=10000)' (type <class 'sklearn.neural_network._multilayer_perceptron.MLPRegressor'>) doesn't

In [45]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

# TODO implement better activation function with custom MLP regressor class with embedded forward pass
# TODO update model with the updated dataset columns

# Custom MLPRegressor with transform method
class CustomMLPRegressor(MLPRegressor):
    def transform(self, X):
        return softmax(self.predict(X))

# Custom activation function to normalize the output
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

data = pd.read_csv('/home/ssj/CS640-Originality-Score-Project/data/AI_data.csv')
data = data.drop(['Unnamed: 8', 'DetectGPT', 'GPT Zero '], axis=1)
data.dropna(inplace=True)

# data.head(10)

data['Label'] = 1
y_pred = data.iloc[:, 2:6].values
# print(y_pred)
y_true = data['Label'].values

scaler = StandardScaler()
y_pred = scaler.fit_transform(y_pred)

mlp = CustomMLPRegressor(hidden_layer_sizes=(10,7,4), activation='relu', solver='adam', max_iter=10000)

mlp.fit(y_pred, y_true)

weights = mlp.coefs_[-1]  # Access the last layer weights

abs_weights_sum = np.sum(np.abs(weights))

normalized_weights = weights / abs_weights_sum

print("Weights obtained:\n")
print("Open AI Classifier:", normalized_weights[0][0])
print("GPT Zero:(perplexity)", normalized_weights[1][0])
print("GPT Zero:(burstiness)", normalized_weights[2][0])
print("DetectGPT:(Z score)", normalized_weights[3][0])
print("\n")

# y_combined = np.dot(y_pred, normalized_weights)
# print("Predicted labels:\n", y_pred)

print("sum of weights:\n", 
      np.abs(normalized_weights[0][0])+np.abs(normalized_weights[1][0])+
      np.abs(normalized_weights[2][0])+np.abs(normalized_weights[3][0]))


Weights obtained:

Open AI Classifier: 0.19331599597683388
GPT Zero:(perplexity) 0.10254274536930445
GPT Zero:(burstiness) -0.29176235559384267
DetectGPT:(Z score) 0.412378903060019


sum of weights:
 1.0
